# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${env:SERVERLESS_ORG}
# "service" is the name of this project. This will also be added to your AWS resource names.
service: HotellBokning

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  getRooms:
    handler: functions/getRooms/index.handler
    events:
      - httpApi:
          path: /rooms
          method: GET
  getBookings:
    handler: functions/getBookings/index.handler
    events:
      - httpApi:
          path: /bookings
          method: GET
  deleteBookings:
    handler: functions/deleteBookings/index.handler
    events:
      - httpApi:
          path: /deleteBookings/{bookingNr}
          method: DELETE
  postBooking:
    handler: functions/postBooking/index.handler
    events:
      - httpApi:
          path: /booking
          method: POST

resources:
  Resources:
    RoomsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rooms-table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    BookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: booking-table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
